# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'demo', 'classify_image']

# %% app.ipynb 1
from fastai.vision.all import *
from duckduckgo_search import DDGS
from fastdownload import download_url
import gradio as gr

# %% app.ipynb 2
learn = load_learner('model.pkl')

# %% app.ipynb 6
categories = ("bee", "humvee", "three", "tree")
def classify_image(img):
    classification_probs = learn.predict(img)[2]
    return dict(zip(categories, map(float, classification_probs)))

# %% app.ipynb 7
image = gr.Image()
label = gr.Label()
examples = ["bee.jpg", "humvee.jpg", "three.jpg", "tree.jpg"]

demo = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
demo.launch()
